In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [2]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [3]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\YOUR_USERNAME\Downloads\customer_shopping_behavior.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YOUR_USERNAME\\Downloads\\customer_shopping_behavior.csv'

In [ ]:
customer_shopping_behavior.csv

In [5]:
import pandas as pd

df = pd.read_csv(r"C:\Users\YOUR_USERNAME\Downloads\customer_shopping_behavior.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YOUR_USERNAME\\Downloads\\customer_shopping_behavior.csv'

In [6]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [7]:
import os 
print(os.listdir())

['.anaconda', '.conda', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.virtual_documents', '.vscode', '24a31a4647', 'add.py', 'app.py', 'AppData', 'Application Data', 'audio', 'audio.py', 'Contacts', 'Cookies', 'Customer_Shopping_Behavior_Analysis.ipynb', 'Documents', 'Downloads', 'Dropbox', 'Favorites', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TM.blf', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'tcs', 'Templates', 'Untitled-1.powerbi.txt', 'Untitled-1.txt', 'Untitled.ipynb', 'Videos', 'vscode projects', 'WPS Cloud Files', 'WPSDrive']

In [8]:
import os
os.chdir("Downloads")

In [9]:
import pandas as pd
pd.read_csv("customer_shopping_behavior.csv")
df.head

NameError: name 'df' is not defined

In [10]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")
df.head

<bound method NDFrame.head of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [11]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [15]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [16]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [17]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace('  ', '_ ')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [18]:
df.columns()

TypeError: 'Index' object is not callable

In [19]:
df.columns

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='object')

In [20]:
labels=["Young Adult","Adult,"Middle-aged","senior"]
d["age-group"]=pd.cut(df["age"],q=4,labels=labels)

SyntaxError: unterminated string literal (detected at line 1) (2993140366.py, line 1)

In [21]:
labels=["Young Adult","Adult","Middle-aged","senior"]
d["age-group"]=pd.cut(df["age"],q=4,labels=labels)

TypeError: cut() got an unexpected keyword argument 'q'

In [22]:
labels=["Young Adult","Adult,"Middle-aged","senior"]
d["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

SyntaxError: unterminated string literal (detected at line 1) (920296318.py, line 1)

In [23]:
labels=["Young Adult","Adult","Middle-aged","senior"]
d["age-group"]=pd.cut(df["age"],q=4,labels=labels)

TypeError: cut() got an unexpected keyword argument 'q'

In [24]:
labels=["Young Adult","Adult","Middle-aged","senior"]
d["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

NameError: name 'd' is not defined

In [25]:
labels=["Young Adult","Adult',"Middle-aged","senior"]
df["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

SyntaxError: unterminated string literal (detected at line 1) (1135868561.py, line 1)

In [26]:
 labels=["Young Adult","Adult","Middle-aged","senior"]
df["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

IndentationError: unexpected indent (2685099891.py, line 1)

In [27]:
labels=["Young Adult","Adult',"Middle-aged","senior"]
df["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

SyntaxError: unterminated string literal (detected at line 1) (1135868561.py, line 1)

In [28]:
labels=["Young Adult","Adult","Middle-aged","senior"]
df["age-group"]=pd.qcut(df["age"],q=4,labels=labels)

In [29]:
df[["age","age_group"]].head(10)

KeyError: "['age_group'] not in index"

In [30]:
df[['age','age_group']].head(10)

KeyError: "['age_group'] not in index"

In [1]:
df[['age',"age_group"]].head(10)

NameError: name 'df' is not defined

In [2]:
df[['age',"age_group"]].head(10)
df

NameError: name 'df' is not defined

In [ ]:
frequency_mapping = {
    "Fortnighty" : 14,
    "Weekly": 7,
    "Montly":30,
    "Quartely":90,
    "Annually" : 365,
    "Every 3 Months":990
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [4]:
df['frequency_of_purchases'].map(frequency_mapping)

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [5]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")
df.head

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [6]:
df.head()

NameError: name 'df' is not defined

In [7]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.xlsx")
df.head

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.xlsx'

In [8]:
import os
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.virtual_documents',
 '.vscode',
 '24a31a4647',
 'add.py',
 'app.py',
 'AppData',
 'Application Data',
 'audio',
 'audio.py',
 'Contacts',
 'Cookies',
 'Customer_Shopping_Behavior_Analysis.ipynb',
 'Documents',
 'Downloads',
 'Dropbox',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TM.blf',
 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'tcs',
 'Templates',
 'Untitled-1.powerbi.txt',
 'Untitled-1.txt',
 'Untitled.ipynb',
 'Videos',
 'vscode projects',
 'WPS Cloud Files',
 'WPSDrive']

In [9]:
import pandas as pd
df=pd.read_csv('Customer_Shopping_Behavior_Analysis.ipynb')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [10]:
import pandas as pd
df=pd.read_csv('Customer_Shopping_Behavior_Analysis.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Customer_Shopping_Behavior_Analysis.csv'

In [11]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\suren
['.anaconda', '.conda', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.virtual_documents', '.vscode', '24a31a4647', 'add.py', 'app.py', 'AppData', 'Application Data', 'audio', 'audio.py', 'Contacts', 'Cookies', 'Customer_Shopping_Behavior_Analysis.ipynb', 'Documents', 'Downloads', 'Dropbox', 'Favorites', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TM.blf', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{362b1d03-15a2-11f0-be6c-706871307692}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'tcs', 'Templates', 'Untitled-1.powerbi.txt', 'Untitled-1.txt', 'Untitled.ipynb', 'Videos', 'vscode projects', 'WPS Cloud Files', 'WPSDrive']

In [13]:
import pandas as pd

df = pd.read_csv(r"C:\Users\suren\Downloads\Customer_Shopping_Behavior.csv")

In [14]:
import pandas as pd

df = pd.read_csv(r"C:\Users\suren\Downloads\Customer_Shopping_Behavior.csv")
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [ ]:
frequency_mapping = {
    "Fortnighty" : 14,
    "Weekly": 7,
    "Montly":30,
    "Quartely":90,
    "Annually" : 365,
    "Every 3 Months":990
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df['frequency_of_purchases'].map(frequency_mapping)

KeyError: 'frequency_of_purchases'

In [17]:
df[['frequency_of_purchases_days','frequency_of_purchases']].head(10)

KeyError: "None of [Index(['frequency_of_purchases_days', 'frequency_of_purchases'], dtype='object')] are in the [columns]"

In [18]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

KeyError: "None of [Index(['purchase_frequency_days', 'frequency_of_purchases'], dtype='object')] are in the [columns]"

In [ ]:
frequency_mapping = {
    "Fortnighty" : 14,
    "Weekly": 7,
    "Montly":30,
    "Quartely":90,
    "Annually" : 365,
    "Every 3 Months":990
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

KeyError: "None of [Index(['purchase_frequency_days', 'frequency_of_purchases'], dtype='object')] are in the [columns]"

In [20]:
df[['discount_applied','promo_code-used']].head(10)

KeyError: "None of [Index(['discount_applied', 'promo_code-used'], dtype='object')] are in the [columns]"

In [21]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 18.6 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [23]:
from sqlalchemy import create_engine
# Replace placeholders with your actual details

username = "postgres"      # default user
password = "Surendar@1"      # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer behavior"   # the database you created in pgAdmin

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"    # choose any table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

ModuleNotFoundError: No module named 'psycopg2'

In [24]:
import sys
!{sys.executable} -m pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\suren\appdata\roaming\python\python313\site-packages (2.9.12)

In [25]:
import psycopg2
print("psycopg2 installed successfully!")

ModuleNotFoundError: No module named 'psycopg2'

In [26]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Surendar%401@localhost:5432/customer behavior"
)

df.to_sql(
    "customer_shopping",
    engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\suren\Downloads\customer_shopping_behavior.csv")

print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [3]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Surendar%401@localhost:5432/customer behavior"
)

df.to_sql(
    "customer_shopping",
    engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [6]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("customer_shopping_behavior.csv")

engine = create_engine(
    "postgresql+psycopg2://postgres:Surendar%401@localhost:5432/customer behavior"
)

df.to_sql(
    "customer_shopping_behavior",
    engine,
    if_exists="replace",
    index=False
)

print("Imported successfully!")

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [7]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Surendar%401@localhost:5432/customer behavior"
)

df.to_sql(
    "customer_shopping_behavior",
    engine,
    if_exists="replace",
    index=False
)

print("Imported successfully!")

Imported successfully!

In [8]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually